/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	__asm volatile("LDR R1,=#0x20001000");
	__asm volatile("LDR R2,=#0x20001004");
	__asm volatile("LDR R0,[R1]");
	__asm volatile("LDR R1,[R2]");
	__asm volatile("ADD R0,R0,R1");
	__asm volatile("STR R0,[R2]");

	//MOVE CONTENT OF 'C' VARIABLE 'VAL' TO ARM REGISTER R0
	// __asm volatile("assembly op, operand indexing using %# (%0 is 1st op, %1 is 2nd op)": output op (empty) : constraint string 0-n 'r' is constraint character, val is c variable)
	int val = 50;
	__asm volatile("MOV R0, %0": : "r"(val));


	//MRS move from special register to register (read from special reg)
	//MSR move from register to special register (write to special reg)
	//CONTROL register is a special register

	int control_reg;
	//read CONTROL register to control_reg
	__asm volatile("MRS %0,CONTROL":"=r"(control_reg)::);


	// "=r" "+r" "&r"
	// = write-only, used for all output operands
	// + read-write operand, must be listed as an output operand
	// & a register that should be used for output only

	int var1 = 10, var2;

	__asm("MOV %0, %1": "=r"(var2): "r"(var1));
	//         Dst Src       OUTPUT     INPUT

	//copy the contents of a pointer into another variable
	int p1, *p2;
	p2 = (int*)0x20000008;
	__asm volatile("LDR %0,[%1]": "=r"(p1): "r"(p2)); //p1 = *p2
	//                  Dst Src     OUTPUT    INPUT

	for(;;);
}
