/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	/*
	 * 1) When processor is reset, PC (program counter) is loaded with the value 0x0000_0000
	 *
	 * 2) Next, processor reads in the value at memory location 0x0000_0000  to MSP (main stack pointer)
	 * MSP = value @ 0x0000_0000
	 * MSP is the Main Stack Pointer register
	 * This means that the processor first initializes the stack pointer (SP)
	 *
	 * 3) Afterwards, the processor reads the value at memory location 0x0000_0004 into PC (program counter)
	 * That value is the address of the Reset Handler.
	 *
	 * 4) Program Counter (PC) jumps to the Reset Handler
	 *
	 * 5) A Reset Handler is a C or Assembly function written by user to carry out any initializations required.
	 *
	 * 6) The Reset Handler calls the main() function of the application at the very end; after initializations.
	 *
	 *
	 *
	 * Startup File   (vector table directs processor to execute Reset handler after reset)
	 *
	 * Reset_handler()
	 * {
	 *
	 * 	//first piece of code which gets executed after reset
	 *
	 * 	//initializations
	 *
	 * 	main();
	 *
	 * }
	 *
	 * (Processor Reset) -> [Initialize data section] -> [Initialize bss section] -> [Initialize 'C' std library: "__libc_init_array();"] -> [main();]
	 *
	 * This file is found under "Startup" Folder > "startup_stm32f4xxxx.s"
	 *
	 *  */

	for(;;);
}
