/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

/*
 * Cortex M processor Exception Model (M0, M1, M3, M4, M7)
 *
 * 1) What is an exception?
 *    Anything which disturbs the normal operation of the program by changing the operational mode of the processor.
 *
 * There are 2 types of exceptions:
 * 1) system exceptions
 * 2) interrupts
 *
 * What are system exceptions?
 * They are generated by the processor itself internally. Interrupts come from the external world to the processor.
 *
 * Whenever the processor core meets with an exception it changes the operational mode to Handler Mode.
 *
 * There are in total 15 system exceptions supported by the Cortex M processors, and 240 Interrupts.
 * So, in total Cortex M processors support 255 exceptions.
 *
 * __Different System Exceptions__
 * 1) There is room for 15 system exceptions.
 * 2) Exception number 1 is Reset Exception (or system exception)
 * 3) Only 9 implemented System Exceptions. 6 are reserved for future implementations.
 * 4) Exception number 16 is Interrupt 1 (IRQ1)
 *
 * Exceptions:
 * 1) Reset 					   (prio -3 -- highest)
 * 2) NMI (non maskable interrupt) (prio -2)
 * 3) HardFault 				   (prio -1)
 * 4) MemManage					   (vv configurable prio vv)
 * 5) BusFault
 * 6) UsageFault
 * 7-10) Reserved
 * 11) SVCall
 * 12-13) Reserved
 * 14) PendSV
 * 15) SysTick
 * 16+) Interrupt (IRQ)
 *
 * Core Peripheral Registers (PPB - Private Peripheral Bus)
 *
 * __System Control Block (SCB)__
 * The System Control Block (SCB) provides system implementation information and system control. This includes configuration, control, and reporting of the system exceptions.
 * Explore registers from ARM Cortex M4 generic user guide.
 *
 * __SCB Registers:__
 * You can enable fault handlers
 * Get pending status of the fault exceptions
 * Trap processor for divide by zero and unaligned data access attempts
 * Control sleep and sleep wakeup settings
 * Configure the priority of system exceptions
 * Systick timer control and status
 *
 *
 */


int main(void)
{
	for(;;);
}

