/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

/* This function executes in THREAD MODE of the processor */
void generate_interrupt()
{
	//these control register addresses cannot be changed in unprivileged mode.
	//any attempt to change contents in unpriv access level will result in processor fault exception
	uint32_t *pSTIR  = (uint32_t*)0xE000EF00;
	uint32_t *pISER0 = (uint32_t*)0xE000E100;

	//enable IRQ3 interrupt
	*pISER0 |= ( 1 << 3);   //ISER = interrupt set-enable register

	//generate an interrupt from software for IRQ3
	*pSTIR = (3 & 0x1FF); //STIR = Software Trigger Interrupt Register

}

void change_access_level_unpriv(void)
{
	//read
	__asm volatile ("MRS R0,CONTROL");
	//modify
	__asm volatile ("ORR R0,R0,#0x01");
	//write
	__asm volatile ("MSR CONTROL,R0");
}


/* This function executes in THREAD MODE of the processor */
int main(void)
{
	printf("In thread mode : before interrupt\n");

	//RTOS always launch user tasks in unprivileged access level
	//RTOS has two components: kernel level and user level tasks.
	//user task should not modify system level settings of processor
	//user task should not trigger or turn off interrupts
	//before running user task, the kernel can change access level to unpriv then it can launch user task
	//if the unpriv code wants any services, then it can trigger syscall which is serviced by the kernel code

	change_access_level_unpriv();

	generate_interrupt();

	printf("In thread mode : after interrupt\n");

	//       how to switch back??

	// first we went control = 0 -> control = 1 (priv to unpriv)
	// cannot modify control register after switching to unpriv
	// gotta move from thread mode to handler mode to make this change
	// ISR always is privileged access level (control = 0)
	// to change back to privilege you have to trigger interrupt or system exception
	// then go to Handler mode to modify control = 1 there, then return to thread mode


	for(;;);
}

/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void)
{
	printf("In handler mode : ISR\n");
}

/* fault handler catches exception */
void HardFault_Handler(void)
{
	printf("Hard fault detected\n");
	while(1);
}
