/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>

void UsageFaultHandler_c(uint32_t *pMSP);

int fun_divide(int x, int y)
{
	return x/y;
}


//next part of exercise (divide by zero)

int main(void)
{
	//1. Enable all configurable exceptions like usage fault, mem manage fault, and bus fault
		//search system control block in cortex m4 user guide
		//look for system handler control and state register (SHCRS **typo in manual)
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault (if disabled, divide by zero treated as HardFault)

	//2. enable divide by zero trap (go to CCR - configuration and control register 4-19)
	//	 4th bit of CCR register is divide by zero trap
	uint32_t *pCCR = (uint32_t*)0xE000ED14;
	*pCCR |= (1 << 4);

	//3. Attempt to divide by zero
	fun_divide(10,0);

	for(;;);
}


//implement the fault handlers
void HardFault_Handler(void)
{
	printf("Exception : HardFault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Exception : BusFault\n");
	while(1);
}

//caller
__attribute__((naked)) void UsageFault_Handler(void){
	//here we extracted the value of MSP which happens to be the base address
	//of the stack frame which got saved during the exception entry from thread mode to handler mode.
	__asm ("MRS r0, MSP");
	__asm ("B UsageFault_Handler_c"); //branch to c function
}

//callee (value of r0 from caller becomes argument 1 in callee function)
void UsageFault_Handler_c(uint32_t *pBaseStackFrame)
{
	// moved these instructions to the naked function above (diff way to do it)
	//__asm ("MRS r0, MSP");
	//register uint32_t msp_value __asm("r0");
	//uint32_t *pMSP = (uint32_t*)msp_value;

	uint32_t *pUFSR = (uint32_t*)0xE000ED2A;
	printf("Exception : UsageFault\n");
	printf("UFSR = %lx\n", (*pUFSR) & 0xFFFF); //read first 16 bits of UFSR register
	//printf("MSP = %p\n", pMSP); //read MSP register

	//print contents of stack frame
	printf("pBaseStackFrame = %p\n", pBaseStackFrame); //read Base of Stack Frame
	printf("Value of R0 = %lx\n", pBaseStackFrame[0]); //read R0 register
	printf("Value of R1 = %lx\n", pBaseStackFrame[1]); //read R1 register
	printf("Value of R2 = %lx\n", pBaseStackFrame[2]); //read R2 register
	printf("Value of R3 = %lx\n", pBaseStackFrame[3]); //read R3 register
	printf("Value of R12 = %lx\n", pBaseStackFrame[4]); //read R12 register
	printf("Value of LR = %lx\n", pBaseStackFrame[5]); //read LR register
	printf("Value of PC = %lx\n", pBaseStackFrame[6]); //read PC register
	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]); //read XPSR register
	while(1);
}
