/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>

#define ALIAS_BASE 0x22000000U
#define BITBAND_BASE 0x20000000U

int main(void)
{
	//Q1. Calculate the bit band alias address for given bit band memory address and bit position.
	//Q2. 7th bit position of the memory location 0x2000_0200 using its alias address

	//General Formula:
	//Alias address = alias_base + (32 * (bit_band_memory_addr - bit_band_base)) + bit * 4

	//A1.             0x2200 0000 + [32 * (0x2000 0200 - 0x2000 0000)] + 7 * 4 =

	uint8_t *ptr = (uint8_t*)0x20000200;

	//reset to 0xff
	*ptr = 0xff;

	//normal method
	*ptr &= ~(1 << 7);

	//reset to 0xff
	*ptr = 0xff;

	//bit-band method
	uint8_t *alias_addr = (uint8_t*) (ALIAS_BASE + (32 * (0x20000200 - BITBAND_BASE)) + 7 * 4);

	//clearing 7th bit of address 0x20000200
	*alias_addr = 0;

	for(;;);
}
